export { map } from './map'
export { filter } from './filter'
export { takeFirst } from './take-first'
export { skip } from './skip'
export { takeWhile } from './take-while'
export { skipUntil } from './skip-until'
export { restMap } from './rest-map'
export { difference, differenceWith, differenceBy } from './difference'
export { intersection, intersectionWith, intersectionBy } from './intersection'
export { flatten, flattenDeep } from './flatten'
export { slice } from './slice'
export { uniqueWith, uniqueBy, unique } from './unique'
export { sortedUniqueBy, sortedUnique } from './sorted-unique'
export { zip, zipStrict } from './zip'
export { pairs, _pairs } from './pairs' // TODO: remove later, testing something
export { tap } from './tap'
export { flatMap } from './flat-map'
